export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_EDIT_INFO = 'USER_EDIT_INFO';

export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST';
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL';
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS';
export const CONTENT_EDIT_INFO = 'CONTENT_EDIT_INFO';

export const HOME_NEW_LIST_SUCCESS = 'HOME_NEW_LIST_SUCCESS';
export const WEB_LIST_SUCCESS = 'WEB_LIST_SUCCESS';
export const MOBILE_LIST_SUCCESS = 'MOBILE_LIST_SUCCESS';
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS';
export const UI_LIST_SUCCESS = 'UI_LIST_SUCCESS';
export const WORDPRESS_LIST_SUCCESS = 'UI_LIST_SUCCESS';
export const RECORD_LIST_SUCCESS = 'UI_LIST_SUCCESS';
export const CODE_LIST_SUCCESS = 'UI_LIST_SUCCESS';

export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS';
